movies/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),

    path('search/', views.search_movies, name='search_movies'),
    
    path('new_movie/', views.new_movie, name='new_movie'),
    
    path('movies/', views.all_movies, name='all_movies'),
    
    path('view_movie/<int:movie_id>', views.view_movie, name='view_movie'),

    path('edit_movie/<int:movie_id>/', views.edit_movie, name='edit_movie'),

    path('delete_movie/<int:movie_id>/', views.delete_movie, name='delete_movie'),
    
    path('view-profile/<int:movie_id>/', views.view_profile, name='view_profile'),

    path('viewcommentprofile/<int:comment_id>/', views.view_comment_profile, name='view_comment_profile'),   

    path('like/<int:movie_id>/', views.like_movie, name='like_movie'),

    path('view_movie/<int:movie_id>/new_comment/', views.new_comment, name='new_comment'),

    path('edit_comment/<int:comment_id>/', views.edit_comment, name='edit_comment'),
]

movies/templates/movies/edit_movie.html
{% extends "base.html" %}

{% block content %}

<fieldset name="Video File Upload and Display">
    {% if msg %} {% autoescape off %} {{ msg }} {% endautoescape %} {% endif %}

    <form method="post" action="{% url 'movies:edit_movie' movie.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <button type="submit">Update Movie Details </button>
        </p>
    </form>
</fieldset>

{% endblock content %}

movies/templates/movies/login copy.html
{% extends "base.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit" class="btn btn-primary">Log In</button>

    <input type="hidden" name="next" value="{% url 'movies:index' %}" />
</form>

{% endblock content %}

movies/templates/movies/movies.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/a097a6cb27.js" crossorigin="anonymous"></script>
    <title>Explore</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            list-style: none;
            border: none;

        }

        body {
            background-color: #f9f9f9;
            font-family: Inter, sans-serif;
        }

        img {
            max-width: 100%;
        }

        .container {
            margin-left: 16%;
        }




        .button-primary {
            background-color: #00A9A5;
            color: #fff;
        }

        .button-secondary {
            background: #EEEEEE;
            color: #00A9A5;
        }

        a {
            text-decoration: none;
            color: inherit;
        }

        .page-padding {
            padding-inline: 32px;
        }

        .padding-vertical-large {
            padding: 96px 0;
        }

        .padding-vertical-small {
            padding: 20px 0;
        }

        .navbar {
            position: sticky;
            top: 0;
            position: -webkit-sticky;
            background-color: white;
            padding: 16px 0;
            box-shadow: 0px 0px 42px rgba(0, 27, 29, 0.08);
            z-index: 999;
        }

        .nav_block-left {
            display: flex;
            align-items: center;
            gap: 16px;
        }

        .nav_block-right {
            display: flex;
            align-items: center;
            gap: 26px
        }

        .navbar-brand {
            max-width: 65.6px;
        }

        .side-nav {
            width: 15.5%;
            background-color: white;
            height: 100vh;
            position: fixed;
            padding-top: 128px;
            top: 0;
            left: 0;
            box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.12);
            z-index: 998;
            overflow: auto;
        }

        .side-nav_links {
            display: flex;
            align-items: center;
            gap: 24px;
            width: 100%;
            padding: 24px 34px;
            font-size: 12px;
        }

        .side-nav_links.active {
            background-color: #F5F5F5;
        }

        .nav-wrapper {
            display: grid;
            grid-template-columns: 1fr 2fr 1fr;
            align-items: center;
        }

        .nav-menu {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .nav_block-left {
            flex-shrink: 0;
        }

        .nav_block-right {
            display: flex;
            align-items: center;
            justify-content: flex-end;
        }

        .nav-links-wrapper {
            display: flex;
        }

        .form-inline {
            display: flex;
        }

        .form-control {
            padding: .75rem 1rem;
            width: 20rem;
            border: 1px solid #737171;
            border-radius: 4px 0px 0px 4px;
        }

        .button {
            padding: 8px 16px;
            border-radius: 8px;
            font-weight: 700;
            font-size: 14px;
            line-height: 24px;
        }

        .nav-mic {
            background-color: rgba(0, 0, 0, 0);
        }

        .button-search {
            padding: 12px 16px;
            background: #EEEEEE;
            border-width: 1px 1px 1px 0px;
            border-style: solid;
            border-color: #737171;
            border-radius: 0px 4px 4px 0px;
            color: #737171;
        }

        .nav_button-wrapper {
            display: flex;
            gap: 16px;
        }

        .filter-tag-wrapper {
            display: flex;
            flex-wrap: wrap;
            align-items: center;
            gap: 32px;
        }

        .filter-tag {
            font-weight: 400;
        }

        .filter-tag.active {
            background: #00A9A5;
            color: #fff;
            padding-inline: 26px;
        }

        .explore_content-wrapper {
            display: flex;
            flex-wrap: wrap;
            gap: 24px;
        }

        .card-body {
            display: flex;
            padding: 1rem 0;
        }

        .thumbnail {
            width: 32px;
            height: 32px;
            flex-shrink: 0;
            background-color: rgba(0, 0, 0, .1);
            border-radius: 50%;
            margin-right: 16px;
        }

        .card-title {
            font-size: 16px;
            font-weight: 500;
        }

        .card {
            width: 23.3%;
            min-width: 260px;
        }

        .card-img-top {
            width: 100%;
        }

        .video-desc p {
            color: #737171;
            line-height: 2;
            font-size: 12px;
            margin-top: 8px;
        }

        .video-info {
            display: flex;
            align-items: center;
        }

        @media only screen and (max-width: 1390px) {
            .card {
                width: 30%;
            }

        }

        @media only screen and (max-width: 1055px) {
            .card {
                width: 48%;
            }

            .side-nav {
                display: none;
            }

            .container {
                margin-left: 0;
            }


        }

        @media only screen and (max-width: 767px) {
            .card {
                width: 100%;
                max-width: 396px;
            }

            .side-nav {
                display: none;
            }

            .upload-video-icon {
                display: none;
            }

            .nav-mic {
                display: none;
            }

            .container {
                margin-left: 0;
            }

            .filter-tag-wrapper {
                display: none;
            }

            .page-padding {
                padding-inline: 16px;
            }
        }
    </style>


{% include 'movies/navbar.html' %}
</head>

<body>
    {% load static %}
    {% include 'movies/sidebar.html' %}
    <main>
        <section class="section-filtertags">
            <div class="page-padding">
                <div class="container">
                    <div class="padding-vertical-small">
                        <div class="filter-tag-wrapper">
                            <button class="button filter-tag active">All</button>
                            <button class="button filter-tag">Comedy</button>
                            <button class="button filter-tag">Learning</button>
                            <button class="button filter-tag">Beauty</button>
                            <button class="button filter-tag">Coding</button>
                            <button class="button filter-tag">Animation</button>
                            <button class="button filter-tag">Cooking</button>
                            <button class="button filter-tag">Action</button>
                            <button class="button filter-tag">UI/UX</button>
                        </div>
                    </div>

                </div>
            </div>

        </section>
        <section>
            <div class="page-padding">
                <div class="container">
                    <div class="padding-vertical-small">
                        <div class="explore_content-wrapper">
                            {% for movie in page_obj %}
                            <div class="card">
                                <div>
                                    <a href="{% url 'movies:view_movie' movie.id %}">
                                        <video class="card-img-top" width="320" height="150" controlsList="nodownload">
                                            <source src="{{ MEDIA_URL }}/{{ movie.video }}" type="video/mp4">
                                        </video>
                                    </a>
                                </div>

                                <div class="card-body">
                                    <div class="thumbnail" style="margin-bottom: 0px;">
                                        {% if  movie.author.userinfo.avatar %}
                                        <a href="{% url 'movies:view_profile' movie.id %}"><img src="{{ movie.author.userinfo.avatar.url }}" alt=""></a>
                                        {% else %}
                                        <a href="{% url 'movies:view_profile' movie.id %}"><img src="{% static 'dummy.png' %}" alt=""></a>
                                        {% endif %}
                                    </div>
                                    <div class="video-desc">
                                        <h3 class="card-title"><a href="{% url 'movies:view_movie' movie.id %}">{{ movie.title }}</a>  
                                        </h3>
                                        <p>
                                            {% if movie.description %}
                                                {{ movie.description }}
                                            {% else %}
                                                No Description has been added!
                                            {% endif %}
                                        </p>
                                        <div class="video-info">
                                            <p class="video-views">{{ movie.liked.count }} Likes</p>
                                            <p class="video-publish-date">| {{ movie.updated }}</p>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            {% empty %}

                            <h3>
                                No Movies have been added yet.
                            </h3>

                            <li><a class="nav-link" href="{% url 'movies:new_movie'%}">Add Movie</a></li>
                    
                            {% endfor  %}

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    <script src="main.js"></script>
</body>

</html>

movies/templates/movies/new_comment.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'movies:view_movie' movie.id %}">{{ movie }}</a></h2>

	<div style="margin: 10px auto;">
		<video autoplay="autoplay" controls controlsList="nodownload preload=" preload">
			<source src="{{ MEDIA_URL }}/{{ movie.video }}" type="video/mp4">
			</source>
		</video>
	</div>
	<div style="margin: 10px auto;">
		<h1>
			<a href="{{movie.video.url}}">Download</a>
	
		</h1>
	</div>

<fieldset name="Video File Upload and Display">
		{% if msg %} {% autoescape off %} {{ msg }} {% endautoescape %} {% endif %}
	<form method="post" action="{% url 'movies:new_comment' movie.id %}">
		{% csrf_token %}
		<dl>
			{{ form.as_p }}
		<p>
			<input type="submit" value="Add Comment">
		</p>
	</form>
</fieldset> 	

{% endblock content %}

movies/templates/movies/sidebar.html
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap');
    
    .side {
    position: fixed;

    width: 220px;
    background-color: var(--txt);
    }

    .sidebar {
    width: 100%;
    height: 120vh;
    color: var(--txt2);
    display: flex;
    flex-direction: column;
    box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.12);
    align-items: center;
    gap: 10px;
    }

    .sidebar h1 {
    display: block;
    padding: 30px 73px;
    }

    .sidebar .sidelist {
    display: flex;
    flex-direction: column;
    gap: 10px;
    }

    .sidelist li {
    display: flex;
    align-items: center;
    padding: 20px 40px;
    }

    .sidelist li:hover {
    background-color: var(--bkg2);
    }

    .sidelist li a {
    display: flex;
    align-items: center;
    font-size: 14px;
    color: var(--txt2);
    gap: 10px;
    }

    .sidelist li a:hover {
    color: var(--bkg);
    filter: invert(43%) sepia(98%) saturate(2578%) hue-rotate(150deg) brightness(97%) contrast(101%);
    }

    .sidelist li a .icons {
    width: 20px;
    }

    .topnav .rightnav .icons {
        width: 22px;
    }

</style>
{% load static %}

<section class="side">
    <nav class="sidebar">
        <ul class="sidelist"><br><br>
            <h1>Settings</h1>
            <li><a href="{% url 'movies:index' %}"><img class="icons" src="{% static 'assets/home3.svg' %}"
                        alt="">Home</a></li>
            <li><a href="{% url 'movies:all_movies' %}"><img class="icons" src="{% static 'assets/library.svg' %} " alt="">Library</a></li>
            {% if user.userinfo.user_type == 'Student' %}
            <li><a href="{% url 'movies:new_movie' %}"><img class="icons" src="{% static 'assets/myvideo.svg' %}" alt="">Upload Video</a></li>
            {% endif %}
            <hr>
            <li><a href="{% url 'accounts:profile' %}"><img class="icons" src="{% static 'assets/settings.svg' %}" alt="">Settings</a></li>
            <li><a href="#"><img class="icons" src="{% static 'assets/help.svg' %}" alt="">Help</a>
            </li>
            {% if user.is_authenticated %}
             <li><a href="{% url 'accounts:logout' %}">Log Out</a>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Log In</a> 
            {% endif %}   
            </li>
        </ul>
    </nav>
</section>

movies/templates/movies/view_movie.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Watch page</title>
    <link rel="stylesheet" href="{% static 'css/watch.css' %}">
</head>

<body>
    <!-- Registered Nav Bar HTML -->

    <div class="container">
        {% include 'movies/navbar.html' %}
    </div>
    
    <div class="container play-container">
        <div class="row">
            <div class="play-video">
                <video controls autoplay>
                    <source src="{{ MEDIA_URL }}/{{ movie.video }}" type="video/mp4">
                </video>
                <div class="play-back-div">
                    <div class="play-back-a">
                        <a class="image-a" href="#"><img
                                src="{% static 'assets/Watch page/Back-forward.png' %}"></a>
                        <a class="image-a" href="#"><img
                                src="{% static 'assets/Watch page/play.png' %}"></a>
                        <a class="image-a" href=""><img
                                src="{% static 'assets/Watch page/fast-forward.png' %}"></a>
                        <a class="image-a volume" href="#"><img
                                src="{% static 'assets/Watch page/volume-up-fill.png' %}"></a>
                    </div>
                    <div class="play-back-b">
                        <a class="image-b" href="#"><img
                                src="{% static 'assets/Watch page/settings.png' %}"></a>
                        <a class="image-b" href=""> 0:00/15:00</a>
                        <a class="image-b" href=""><img
                                src="{% static 'assets/Watch page/maximize-2.png' %}"></a>
                    </div>
                </div>

                <div class="play-video-info">
                    <div class="video-heading">
                        <h3>{{ movie.title }}</h3>
                        <div>
                            <a href="">
                                <form action="{% url 'movies:like_movie' movie.id %}" method="POST">
                                    {% csrf_token %}
                                    {% if lik %}
                                    <button style="background-color: red;" type="submit">Unlike</button>
                                    {% else %}
                                    <button style="background-color: greenyellow;" type="submit">Like</button>
                                    {% endif %}
                                </form>
                                {% if movie.liked.count == 1 %} 
                                          1 Like 
                                {% else %} 
                                <strong>
                                    {{ movie.liked.count }} Likes 
                                </strong>
                                {% endif %}
                            </a>

                            <a href=""><img
                                    src="{% static 'assets/Watch page/share-line.png' %}">share</a>
                            <a href=""><img src="{% static 'assets/Watch page/hq-line.png' %}">Video
                                quality</a>
                            {% if movie.author == request.user %}
                            <a href="{% url 'movies:delete_movie' movie.id %}">Delete</a>
                            {% endif %}
                            
                            <a href=""><img
                                    src="{% static 'assets/Watch page/heart-add-line.png' %}">
                                    {% if fav %}
                                    <a href="{% url 'accounts:add_favourite' movie.id %}">Unsave</a>
                                    {% else %}
                                    <a href="{% url 'accounts:add_favourite' movie.id %}">Save</a>
                                    {% endif %}
                                </a>
                        </div>
                    </div>
                    <p>0 Views &bull; {{movie.created}}</p>
                </div>
                <hr>
                <div class="publisher">
                    {% if movie.author.userinfo.avatar %}
                    <a href="{% url 'movies:view_profile' movie.id  %}"><img style="width:50px;" src="{{ movie.author.userinfo.avatar.url }}" alt="{{ movie.author }} avatar"></a>
                    {% else %}
                    <a href="{% url 'movies:view_profile' movie.id  %}"><img src="{% static 'dummy.png' %}" alt="My image"></a>
                    {% endif %}
                    <div>
                        <p>
                            <a href="{% url 'movies:view_profile' movie.id  %}">{{movie.author}}</a>
                        </p>
                        <span>0 Subscribers</span>
                        <div class="sub-button">
                            <button type="button">Subscribe</button>
                        </div>
                    </div>
                    <p>{{movie.description}}</p>
                </div>
                
                <div class="vid-description">
                    <h4>Drop a comment</h4>

                    <div class="add-comment">                    
                        
                        {% if request.user.userinfo.avatar %}
                        <img style="width:50px;" src="{{ request.user.userinfo.avatar.url }}"alt="Your avatar">
                        {% else %}
                        <img src="{% static 'dummy.png' %}" alt="My image">
                        {% endif %}
                        
                        <form method="post" action="{% url 'movies:new_comment' movie.id %}" value="{{ request.POST.comment_text }}">
                            {% csrf_token %}
                                <textarea type="text" name="comment_text" value="{{ request.POST.comment_text }}"
                                    placeholder="Add your comment here">
                                </textarea>

                                <div class="comment-button">
                                    <button>Post comment</button>
                                </div>
                        </form>            
                    </div>

                {% for comment in comments %}    
                <div class="old-comment">

                    {% if comment.comment_author.userinfo.avatar %}
                    <a href="{% url 'movies:view_comment_profile' comment.id  %}"><img style="width:50px;"
                            src="{{ comment.comment_author.userinfo.avatar.url }}" alt=""></a>
                    
                    {% else %}
                    <a href="{% url 'movies:view_comment_profile' comment.id  %}"><img src="{% static 'dummy.png' %}" alt="My image"></a>
                    {% endif %}

                    {% if comment.comment_author.userinfo.avatar %}
                    <a href="{% url 'movies:view_comment_profile' comment.id  %}"><img style="width:50px;" src="{{ comment.comment_author.userinfo.avatar.url }}" alt=""></a>
                    
                    {% else %}
                    <a href="{% url 'movies:view_comment_profile' comment.id  %}"><img src="{% static 'dummy.png' %}" alt="My image"></a>
                    {% endif %}


                    <div>
                        <h3> 
                            <a href="{% url 'movies:view_comment_profile' comment.id  %}">{{ comment.comment_author }}</a>
                            <span>{{comment.date_added}}</span>
                        </h3>
                        <p>{{comment.comment_text}}</p>
                        <div class="comment-action">
                                {% if request.user == comment.comment_author %}
                                <span>
                                    <a href="{% url 'movies:edit_comment' comment.id %}">EDIT</a>
                                </span>
                                {% endif %}
                            <!-- <a href="">View replies <span><img src="/beta/COL_FILMS_TEAM_114/" alt=""></span></a> -->
                            <div class="comment-action-icons">
                                <img src="{% static 'assets/Watch page/thumb-up-line.png' %}">
                                <span>0</span>
                                <img src="{% static 'assets/Watch page/thumb-down-line.png' %}">
                                <span>0</span>
                                <!-- {% if request.user == comment.comment_author %}
                                <span>
                                    <a href="{% url 'movies:edit_comment' comment.id %}">EDIT</a>
                                </span>
                                {% endif %} -->
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

                </div>
                </div>
                <div class="right-sidebar">
                    <h3>Selected just for you</h3>
                
                    <div class="side-video-list">
                        <a href="" class="small-thumbnail"><img
                                src="{% static 'assets/Watch page/Frame 61.png' %}"></a>
                        <div class="video-info-container">
                            <div>
                                <button"><img style="border-radius: 100%; width: 32px;"
                                        src="{% static 'assets/Watch page/Ellipse 5.png' %}" alt=""></button>
                            </div>
                            <div class="vid-info">
                                <a href="">Why Business sucks by a business student</a>
                                <p>Your Business Girl</p>
                                <p>100k Views | 5 months ago</p>
                            </div>
                        </div>
                    </div>
                
                    <div>
                        <div class="sneak-peaks-text flex">
                            <img src="/beta/COL_FILMS_TEAM_114/static/assets/Watch page/sneak peak.svg" alt="">
                            <p>Sneak Peaks</p>
                        </div>
                        <div class="sneak-peaks-img flex">
                            <img src="/beta/COL_FILMS_TEAM_114/static/assets//Watch page/Rectangle 114.png" alt="">
                            <img src="/beta/COL_FILMS_TEAM_114/static/assets/Watch page/Rectangle 115.png" alt="">
                            <img src="/beta/COL_FILMS_TEAM_114/static/assets/Watch page/Rectangle 116.png" alt="">
                        </div>
                    </div>
                
                    <div class="side-video-list">
                        <a href="" class="small-thumbnail"><img
                                src="{% static 'assets/Watch page/Frame 61-1.png' %}"></a>
                        <div class="video-info-container">
                            <div>
                                <button"><img style="border-radius: 100%; width: 32px;"
                                        src="/beta/COL_FILMS_TEAM_114/static/assets/Watch page/Ellipse 5-1.png" alt=""></button>
                            </div>
                            <div class="vid-info">
                                <a href="">Teaching the art of optical tricks professionally</a>
                                <p>Your Business Guy</p>
                                <p>100k Views | 5 months ago</p>
                            </div>
                        </div>
                
                    </div>
                    <div class="side-video-list">
                        <a href="" class="small-thumbnail"><img
                                src="{% static 'assets/Watch page/Frame 61-2.png' %}"></a>
                        <div class="video-info-container">
                            <div>
                                <button"><img style="border-radius: 100%; width: 32px;"
                                        src="{% static 'assets/Watch page/Ellipse 5-2.png' %}" alt=""></button>
                            </div>
                            <div class="vid-info">
                                <a href="">10 DIY ways to make crafty photo Frames!!!</a>
                                <p>Your Business Guy</p>
                                <p>100k Views | 5 months ago</p>
                            </div>
                        </div>
                
                    </div>
                    <h3>from your last watch</h3>
                    <div class="side-video-list">
                        <a href="" class="small-thumbnail"><img
                                src="{% static 'assets/Watch page/Frame 61-3.png' %}"></a>
                    </div>
                </div>
                </div>
                </div>
                </div>
                
                
                </body>
                
                </html>

movies/templates/movies/viewcommentprofile copy.html
{% extends "base.html" %}

{% block page_header %}
<h2>Log in to your account.</h2>
{% endblock page_header %}

{% block content %}

    <h1>
        User Details
    </h1>
    <h3>
        {{ user.username }}
        <br>
        {{ user.userinfo.user_type }}

    </h3> 

    <h1>Lists of all User's Videos </h1>

    {% for movie in movies %}

    <a href="{% url 'movies:view_movie' movie.id %}">
        <video width="320" height="240" controlsList="nodownload">
            <source src="{{ MEDIA_URL }}/{{ movie.video }}" type="video/mp4">
        </video>
    </a>

    {% empty %}

    <h3>
        No movie Yet!
    </h3>
    {% endfor %}

{% endblock content %}

movies/templates/movies/viewprofile copy.html
{% extends "base.html" %}

{% block page_header %}
<h2>Log in to your account.</h2>
{% endblock page_header %}

{% block content %}
    <h1>
        User Details
    </h1>
    <h3>
        {{ user.username }}
        <br>
        {{ user.userinfo.user_type }}

    </h3> 

    <h1>Lists of all User's Videos </h1>

    {% for movie in movies %}

    <a href="{% url 'movies:view_movie' movie.id %}">
        <video width="320" height="240" controlsList="nodownload">
            <source src="{{ MEDIA_URL }}/{{ movie.video }}" type="video/mp4">
        </video>
    </a>

    {% empty %}

    <h3>
        No movie Yet!
    </h3>
    {% endfor %}

{% endblock content %}